//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryPrj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeShift
    {
        public int EmpShiftID { get; set; }
        public int EmpID { get; set; }
        public int ShiftID { get; set; }
    }
}
